version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10.11
    steps:
      - checkout
      - run: python --version
    steps:
      - checkout
      - setup_remote_docker:
        version: 20.10.14
        docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build  -t phongtn/squat-game:latest .      
      - deploy:
          name: Push application Docker image
          command: |
            # if [ "${CIRCLE_BRANCH}" == "main" ]; then
            docker push phongtn/squat-game:latest
            # fi