version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.11
    steps:
      - checkout
      - run: python --version
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # build and push Docker image
      - run: |
          TAG=0.1
          docker build  -t phongtn/squat-game:latest .      
          docker push phongtn/squat-game:latest 
