version: 2.1

jobs:
  build:
    environment:
      DOCKER_IMAGE: squat-game
      DOCKER_TAG: latest
    docker:
      - image: cimg/python:3.10.11
    steps:
      - checkout
      - run: python --version

      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true     
           
      # build Docker image
      - run: |
          docker build  -t $DOCKER_USER/$DOCKER_IMAGE:$DOCKER_TAG .
      # push Docker image to docker repository    
      - run: |    
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push $DOCKER_USER/$DOCKER_IMAGE:$DOCKER_TAG
